// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(koriumFFI)
import koriumFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_korium_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_korium_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * The main Korium node interface for mobile.
 */
public protocol KoriumNodeProtocol : AnyObject {
    
    /**
     * Add a peer to the routing table.
     */
    func addPeer(identityHex: String, addresses: [String]) throws 
    
    /**
     * Bootstrap by connecting to a known peer.
     */
    func bootstrap(identityHex: String, addresses: [String]) throws 
    
    /**
     * Bootstrap using public seed nodes.
     */
    func bootstrapPublic() throws 
    
    /**
     * Get this node's identity (hex-encoded public key).
     */
    func identity()  -> String
    
    /**
     * Get the local bind address.
     */
    func localAddress() throws  -> String
    
    /**
     * Poll for next received message (non-blocking, returns None if none available).
     */
    func pollMessage() throws  -> PubSubMessage?
    
    /**
     * Publish to a PubSub topic.
     */
    func publish(topic: String, data: Data) throws 
    
    /**
     * Resolve an identity to contact information.
     */
    func resolve(identityHex: String) throws  -> PeerContact?
    
    /**
     * Get routable addresses for this node.
     */
    func routableAddresses()  -> [String]
    
    /**
     * Send a request and wait for response.
     */
    func send(identityHex: String, request: Data) throws  -> Data
    
    /**
     * Shutdown the node.
     */
    func shutdown() 
    
    /**
     * Subscribe to a PubSub topic.
     */
    func subscribe(topic: String) throws 
    
    /**
     * Get list of subscribed topics.
     */
    func subscriptions() throws  -> [String]
    
    /**
     * Get telemetry snapshot.
     */
    func telemetry() throws  -> Telemetry
    
    /**
     * Unsubscribe from a PubSub topic.
     */
    func unsubscribe(topic: String) throws 
    
}

/**
 * The main Korium node interface for mobile.
 */
open class KoriumNode:
    KoriumNodeProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_korium_fn_clone_koriumnode(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_korium_fn_free_koriumnode(pointer, $0) }
    }

    
    /**
     * Create a new node with a fresh identity (includes PoW generation).
     */
public static func create(bindAddress: String)throws  -> KoriumNode {
    return try  FfiConverterTypeKoriumNode.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_constructor_koriumnode_create(
        FfiConverterString.lower(bindAddress),$0
    )
})
}
    
    /**
     * Create a node with an existing identity.
     */
public static func createWithIdentity(bindAddress: String, secretKeyHex: String, nonceHex: String)throws  -> KoriumNode {
    return try  FfiConverterTypeKoriumNode.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_constructor_koriumnode_create_with_identity(
        FfiConverterString.lower(bindAddress),
        FfiConverterString.lower(secretKeyHex),
        FfiConverterString.lower(nonceHex),$0
    )
})
}
    

    
    /**
     * Add a peer to the routing table.
     */
open func addPeer(identityHex: String, addresses: [String])throws  {try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_add_peer(self.uniffiClonePointer(),
        FfiConverterString.lower(identityHex),
        FfiConverterSequenceString.lower(addresses),$0
    )
}
}
    
    /**
     * Bootstrap by connecting to a known peer.
     */
open func bootstrap(identityHex: String, addresses: [String])throws  {try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_bootstrap(self.uniffiClonePointer(),
        FfiConverterString.lower(identityHex),
        FfiConverterSequenceString.lower(addresses),$0
    )
}
}
    
    /**
     * Bootstrap using public seed nodes.
     */
open func bootstrapPublic()throws  {try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_bootstrap_public(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Get this node's identity (hex-encoded public key).
     */
open func identity() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_korium_fn_method_koriumnode_identity(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the local bind address.
     */
open func localAddress()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_local_address(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Poll for next received message (non-blocking, returns None if none available).
     */
open func pollMessage()throws  -> PubSubMessage? {
    return try  FfiConverterOptionTypePubSubMessage.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_poll_message(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Publish to a PubSub topic.
     */
open func publish(topic: String, data: Data)throws  {try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_publish(self.uniffiClonePointer(),
        FfiConverterString.lower(topic),
        FfiConverterData.lower(data),$0
    )
}
}
    
    /**
     * Resolve an identity to contact information.
     */
open func resolve(identityHex: String)throws  -> PeerContact? {
    return try  FfiConverterOptionTypePeerContact.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_resolve(self.uniffiClonePointer(),
        FfiConverterString.lower(identityHex),$0
    )
})
}
    
    /**
     * Get routable addresses for this node.
     */
open func routableAddresses() -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_korium_fn_method_koriumnode_routable_addresses(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Send a request and wait for response.
     */
open func send(identityHex: String, request: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_send(self.uniffiClonePointer(),
        FfiConverterString.lower(identityHex),
        FfiConverterData.lower(request),$0
    )
})
}
    
    /**
     * Shutdown the node.
     */
open func shutdown() {try! rustCall() {
    uniffi_korium_fn_method_koriumnode_shutdown(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Subscribe to a PubSub topic.
     */
open func subscribe(topic: String)throws  {try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_subscribe(self.uniffiClonePointer(),
        FfiConverterString.lower(topic),$0
    )
}
}
    
    /**
     * Get list of subscribed topics.
     */
open func subscriptions()throws  -> [String] {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_subscriptions(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get telemetry snapshot.
     */
open func telemetry()throws  -> Telemetry {
    return try  FfiConverterTypeTelemetry.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_telemetry(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Unsubscribe from a PubSub topic.
     */
open func unsubscribe(topic: String)throws  {try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_method_koriumnode_unsubscribe(self.uniffiClonePointer(),
        FfiConverterString.lower(topic),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKoriumNode: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = KoriumNode

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> KoriumNode {
        return KoriumNode(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: KoriumNode) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KoriumNode {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: KoriumNode, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKoriumNode_lift(_ pointer: UnsafeMutableRawPointer) throws -> KoriumNode {
    return try FfiConverterTypeKoriumNode.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKoriumNode_lower(_ value: KoriumNode) -> UnsafeMutableRawPointer {
    return FfiConverterTypeKoriumNode.lower(value)
}


/**
 * Identity bundle returned from `generate_identity()`.
 */
public struct IdentityBundle {
    public var secretKeyHex: String
    public var identityHex: String
    public var nonceHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(secretKeyHex: String, identityHex: String, nonceHex: String) {
        self.secretKeyHex = secretKeyHex
        self.identityHex = identityHex
        self.nonceHex = nonceHex
    }
}



extension IdentityBundle: Equatable, Hashable {
    public static func ==(lhs: IdentityBundle, rhs: IdentityBundle) -> Bool {
        if lhs.secretKeyHex != rhs.secretKeyHex {
            return false
        }
        if lhs.identityHex != rhs.identityHex {
            return false
        }
        if lhs.nonceHex != rhs.nonceHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(secretKeyHex)
        hasher.combine(identityHex)
        hasher.combine(nonceHex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentityBundle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IdentityBundle {
        return
            try IdentityBundle(
                secretKeyHex: FfiConverterString.read(from: &buf), 
                identityHex: FfiConverterString.read(from: &buf), 
                nonceHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: IdentityBundle, into buf: inout [UInt8]) {
        FfiConverterString.write(value.secretKeyHex, into: &buf)
        FfiConverterString.write(value.identityHex, into: &buf)
        FfiConverterString.write(value.nonceHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityBundle_lift(_ buf: RustBuffer) throws -> IdentityBundle {
    return try FfiConverterTypeIdentityBundle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityBundle_lower(_ value: IdentityBundle) -> RustBuffer {
    return FfiConverterTypeIdentityBundle.lower(value)
}


/**
 * Contact information for a peer.
 */
public struct PeerContact {
    public var identity: String
    public var addresses: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identity: String, addresses: [String]) {
        self.identity = identity
        self.addresses = addresses
    }
}



extension PeerContact: Equatable, Hashable {
    public static func ==(lhs: PeerContact, rhs: PeerContact) -> Bool {
        if lhs.identity != rhs.identity {
            return false
        }
        if lhs.addresses != rhs.addresses {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(identity)
        hasher.combine(addresses)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePeerContact: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PeerContact {
        return
            try PeerContact(
                identity: FfiConverterString.read(from: &buf), 
                addresses: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: PeerContact, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identity, into: &buf)
        FfiConverterSequenceString.write(value.addresses, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePeerContact_lift(_ buf: RustBuffer) throws -> PeerContact {
    return try FfiConverterTypePeerContact.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePeerContact_lower(_ value: PeerContact) -> RustBuffer {
    return FfiConverterTypePeerContact.lower(value)
}


/**
 * A received PubSub message.
 */
public struct PubSubMessage {
    public var topic: String
    public var sourceIdentity: String
    public var data: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(topic: String, sourceIdentity: String, data: Data) {
        self.topic = topic
        self.sourceIdentity = sourceIdentity
        self.data = data
    }
}



extension PubSubMessage: Equatable, Hashable {
    public static func ==(lhs: PubSubMessage, rhs: PubSubMessage) -> Bool {
        if lhs.topic != rhs.topic {
            return false
        }
        if lhs.sourceIdentity != rhs.sourceIdentity {
            return false
        }
        if lhs.data != rhs.data {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(topic)
        hasher.combine(sourceIdentity)
        hasher.combine(data)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePubSubMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PubSubMessage {
        return
            try PubSubMessage(
                topic: FfiConverterString.read(from: &buf), 
                sourceIdentity: FfiConverterString.read(from: &buf), 
                data: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: PubSubMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.topic, into: &buf)
        FfiConverterString.write(value.sourceIdentity, into: &buf)
        FfiConverterData.write(value.data, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePubSubMessage_lift(_ buf: RustBuffer) throws -> PubSubMessage {
    return try FfiConverterTypePubSubMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePubSubMessage_lower(_ value: PubSubMessage) -> RustBuffer {
    return FfiConverterTypePubSubMessage.lower(value)
}


/**
 * Telemetry snapshot.
 */
public struct Telemetry {
    public var storedKeys: UInt64
    public var replicationFactor: UInt64
    public var concurrency: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(storedKeys: UInt64, replicationFactor: UInt64, concurrency: UInt64) {
        self.storedKeys = storedKeys
        self.replicationFactor = replicationFactor
        self.concurrency = concurrency
    }
}



extension Telemetry: Equatable, Hashable {
    public static func ==(lhs: Telemetry, rhs: Telemetry) -> Bool {
        if lhs.storedKeys != rhs.storedKeys {
            return false
        }
        if lhs.replicationFactor != rhs.replicationFactor {
            return false
        }
        if lhs.concurrency != rhs.concurrency {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(storedKeys)
        hasher.combine(replicationFactor)
        hasher.combine(concurrency)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTelemetry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Telemetry {
        return
            try Telemetry(
                storedKeys: FfiConverterUInt64.read(from: &buf), 
                replicationFactor: FfiConverterUInt64.read(from: &buf), 
                concurrency: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Telemetry, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.storedKeys, into: &buf)
        FfiConverterUInt64.write(value.replicationFactor, into: &buf)
        FfiConverterUInt64.write(value.concurrency, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTelemetry_lift(_ buf: RustBuffer) throws -> Telemetry {
    return try FfiConverterTypeTelemetry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTelemetry_lower(_ value: Telemetry) -> RustBuffer {
    return FfiConverterTypeTelemetry.lower(value)
}


/**
 * FFI-safe error type.
 */
public enum KoriumError {

    
    
    case InvalidAddress
    case InvalidIdentity
    case ConnectionFailed
    case Timeout
    case NotConnected
    case AlreadySubscribed
    case NotSubscribed
    case ChannelClosed
    case PowFailed
    case Internal(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKoriumError: FfiConverterRustBuffer {
    typealias SwiftType = KoriumError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KoriumError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidAddress
        case 2: return .InvalidIdentity
        case 3: return .ConnectionFailed
        case 4: return .Timeout
        case 5: return .NotConnected
        case 6: return .AlreadySubscribed
        case 7: return .NotSubscribed
        case 8: return .ChannelClosed
        case 9: return .PowFailed
        case 10: return .Internal(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: KoriumError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .InvalidAddress:
            writeInt(&buf, Int32(1))
        
        
        case .InvalidIdentity:
            writeInt(&buf, Int32(2))
        
        
        case .ConnectionFailed:
            writeInt(&buf, Int32(3))
        
        
        case .Timeout:
            writeInt(&buf, Int32(4))
        
        
        case .NotConnected:
            writeInt(&buf, Int32(5))
        
        
        case .AlreadySubscribed:
            writeInt(&buf, Int32(6))
        
        
        case .NotSubscribed:
            writeInt(&buf, Int32(7))
        
        
        case .ChannelClosed:
            writeInt(&buf, Int32(8))
        
        
        case .PowFailed:
            writeInt(&buf, Int32(9))
        
        
        case let .Internal(msg):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension KoriumError: Equatable, Hashable {}

extension KoriumError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePeerContact: FfiConverterRustBuffer {
    typealias SwiftType = PeerContact?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePeerContact.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePeerContact.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePubSubMessage: FfiConverterRustBuffer {
    typealias SwiftType = PubSubMessage?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePubSubMessage.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePubSubMessage.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Generate a new identity with Proof-of-Work.
 *
 * This is CPU-intensive and takes ~1-4 seconds.
 * Returns the secret key, public identity, and PoW nonce as hex strings.
 */
public func generateIdentity()throws  -> IdentityBundle {
    return try  FfiConverterTypeIdentityBundle.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_func_generate_identity($0
    )
})
}
/**
 * Parse and validate an identity from hex string.
 */
public func identityFromHex(hexStr: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeKoriumError.lift) {
    uniffi_korium_fn_func_identity_from_hex(
        FfiConverterString.lower(hexStr),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_korium_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_korium_checksum_func_generate_identity() != 18102) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_func_identity_from_hex() != 54470) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_add_peer() != 62932) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_bootstrap() != 63808) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_bootstrap_public() != 8639) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_identity() != 2326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_local_address() != 6267) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_poll_message() != 34161) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_publish() != 54605) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_resolve() != 10841) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_routable_addresses() != 13219) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_send() != 62940) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_shutdown() != 8707) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_subscribe() != 9922) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_subscriptions() != 61313) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_telemetry() != 31917) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_method_koriumnode_unsubscribe() != 61365) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_constructor_koriumnode_create() != 23533) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_korium_checksum_constructor_koriumnode_create_with_identity() != 8004) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all